active_arm_joint_name_1: "jaco_joint_1"
active_arm_joint_name_2: "jaco_joint_2"
active_arm_joint_name_3: "jaco_joint_3"
active_arm_joint_name_4: "jaco_joint_4"
active_arm_joint_name_5: "jaco_joint_5"
active_arm_joint_name_6: "jaco_joint_6"

